import { Box, Card, Container, Typography } from "@mui/material";
import BaseCard from "components/Common/Cards/BaseCard";
import SectionTitleText from "components/Common/Typography/HeadingText/SectionTitleText";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import { useEffect } from "react";
import { useSelector } from "react-redux";

const mapState = ({ user }) => ({
	currentUser: user.currentUser,
});
export default function AuthLayout({ pageTitle, headingTitle, children }) {
	const { currentUser } = useSelector(mapState);
	const router = useRouter();
	useEffect(() => {
		if (currentUser) router.push("/home");
	}, [currentUser]);
	return (
		<Box sx={{}}>
			{" "}
			<Head>
				<title>{pageTitle || "Ecommerce Dashboard App"}</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Container>
				<Box
					sx={{
						display: "grid",
						placeItems: "center",
						height: "100vh",
					}}
				>
					<BaseCard
						sx={{
							padding: "32px",
							// borderRadius: "32px",
							minWidth: "500px",
							minHeight: "400px",
						}}
					>
						<SectionTitleText variant="h4">
							{headingTitle || "Log in to your account"}{" "}
						</SectionTitleText>
						<Box>{children}</Box>
					</BaseCard>
				</Box>
			</Container>
		</Box>
	);
}
